services:

  app:
    container_name: hello-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: hello-spring:1.0

    ports:
      - "${APP_PORT}:${SERVER_PORT}"

    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    networks:
      - redis-docker


  redis:
    container_name: redis-docker

    build:
      context: .
      dockerfile: ./docker/dockerfile

    restart: always

    environment:
      REDIS_HOST: localhost
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MEMORY_RELEASE_MAX: ${MEMORY_RELEASE_MAX}

    env_file:
      - .env

    command: /usr/local/bin/script/start_redis.sh

    volumes:
      - ./redis/data:/data/

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    networks:
      - redis-docker

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -a $REDIS_PASSWORD ping"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  redis-docker:
    driver: bridge