services:
  app:
    container_name: hello-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: hello-spring:1.0
    ports:
      - "${APP_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    container_name: redis-docker
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis_data:
